### ISSUE TITLE
Frame:0 : cannot connect to X server

### ISSUE THREAD

**Issue by hxlee309** [ghostbbbmt/Traffic-Sign-Classification#3]
Since I cannot find the default video, I downloaded a video from youtube instead (https://www.youtube.com/watch?v=bs15ve3T8II).
Then an error above is returned. 
Any help will be appreciated.

**Comment by hoanglehaithanh** [comment]
hi @hxlee309 , 
Your error seems to be unable to connect to a display. I searched your error and[ this link](https://askubuntu.com/questions/175611/cannot-connect-to-x-server-when-running-app-with-sudo) might help you 

Were you trying to run the code via SSH? Which device were you using? I ran my project on my laptop with anaconda on Windows 10.

**Comment by hxlee309** [comment]
Yes I was running the code via SSH. I tested it on local station just now and it worked. Thanks for your help!

**Comment by hxlee309** [comment]
Could you provide some good video source? I just tested my video (https://www.youtube.com/watch?v=bs15ve3T8II), and the result is not very good (false detection & miss detection)

**Comment by hoanglehaithanh** [comment]
Hi @hxlee309,
The light condition in your video seems to be different from my test video, so OpenCV can't detect contour as well as find the traffic signs using image processing techniques. That's why I am trying to make a new version using deep learning with an SSD network model (as mentioned in the README). The current method can't adopt new scene well. 

For temporary solutions, try to adjust parameters while running the python script or adjust other parameters in the source code. There are many parameters can be changed during the detection phase. Use OpenCV to show the image after each stage to track your progress,

Good luck and have a nice week!

**Comment by nirmalsnair** [comment]
@ghostbbbmt Could you include the default video `MVI_1049.avi` to check if everything is working as expected?

**Comment by hoanglehaithanh** [comment]
> @ghostbbbmt Could you include the default video `MVI_1049.avi` to check if everything is working as expected?

Done. I have replied your raised issue
